### ISSUE TITLE
additional library discussion

### ISSUE THREAD

**Issue by altayaydemir** [barbar/vortigern#13]
we can discuss adding 3rd party libraries (I mean, other than the core ones) here, I suggest:

- [x] classnames
- [x] redux-thunk
- [ ] immutablejs 💂 

@batuhan @ilgooz

**Comment by batuhan** [comment]
can't we just use Object.assign instead of immutablejs? I know it has additional benefits but are we going to take advantage of those benefits?

classnames is a nice to have, it doesn't add too much overhead to disturb us.

I like redux-thunk. So I'm giving it a +1.

anything you would like to add, @ilgooz?
