### ISSUE TITLE
Is it good idea to use express server for developping API code ?

### ISSUE THREAD

**Issue by mimiz** [barbar/vortigern#154]
Hi, 

First of all thanks a lot for your good work! 
I really appreciate this boilerplate! 

Actually, I planned to create a web application with your boilerplate, and I was thinking of using the express server included for server-side rendering to develop the API of the application.

This, for example, will allow me to share some code between client and server.

My question is quite simple: do you think it's a good idea? 

Regards !

Rémi

**Comment by batuhan** [comment]
Hey @mimiz,

I believe frontend (react bits) and the backend (api) should be decoupled. React is the hot thing today but tomorrow we can all move onto the next hot thing in the market. API's are supposed to be independent of that. 

Decoupling also allows you to use another language/framework in the future with your API too, if you so choose.

You have a few options for code sharing though:

- Build a package (NPM): You can put all of the common utility code inside an NPM library. Keep in mind you can "install" libraries outside of NPM, via Git, HTTP or from local directories. This also allows you version your code, but that's a double edged sword since you would, in theory, need to keep pushing new versions for most of your edits.

- Import it directly: You can create a directory structure with 3 main directories: `frontend`, `api` and `common`. In your API or frontend code, call it with `require('../common')` or the equivalent `import` ES6 syntax. If you use bundling (for example with webpack), this also bundles the common functions inside each application's (api and frontend) own bundle.

Let me know if you have more questions.

_Should also point out I'm no longer part of @barbar, so opinions of them may be different from my own._

**Comment by batuhan** [comment]
You can always _proxy_ the API inside the frontend code, which easily allows you to serve both on the same domain and from the same application. Of course, this all depends on your specific needs.

**Comment by mimiz** [comment]
Hey, @batuhan,

 Thanks a lot for your advice, and I think you are right. Sorry for my late response but I was on holiday AFK! 
  I will follow your ideas !

Regards
Rémi

**Comment by ufukomer** [comment]
https://twitter.com/Todd_McLeod/status/920784947215863808

**Comment by bherila** [comment]
@batuhan what I do is implement my API separately, export a swagger definition file, and then generate a typescript proxy interface which I put in a NPM package. Then I import this API proxy in my react-native code as well as the vortigern-based site. 

I actually implemented the API in C# using ASP.NET Web API which worked really well for my backend needs. All the types are initially defined in C# and Typescript versions of the classes are generated through the swagger toolchain.

Resources: 

1. Swagger: https://swagger.io/
2. Swagger-codegen: https://github.com/swagger-api/swagger-codegen
