### ISSUE TITLE
Optional server side rendering

### ISSUE THREAD

**Issue by batuhan** [barbar/vortigern#57]

**Comment by batuhan** [comment]
Since we'll be releasing Odoacer this week, should we still make server side rendering optional on Vortigern? cc/ @altayaydemir

**Comment by emzero** [comment]
I'd love a way to disable server-side rendering so I could use this inside a ASP.NET Core project.

**Comment by altayaydemir** [comment]
@emzero Hey, since we are kind of busy nowadays we may not be able to publish our other boilerplate (which has client-side rendering and firebase as backend) in a short period of time.

However, as I've stated in #54, you can check out the structure of [this project](https://github.com/bilgishuttle/bilgi-shuttle-web) which has similar configurations with Vortigern, but more lightweight and client-side rendered version.
