### ISSUE TITLE
Isomorphic style loader

### ISSUE THREAD

**Issue by mostlyjason** [barbar/vortigern#76]
I'm noticing a flicker on the screen when loading a new page with caching disabled. I think it's because when the server side renders the page it does not include styles. Eventually, when the styles are downloaded the elements are repositioned to their correct locations. It would be better to include the styles with the server side rendering so there is no flicker.

I found a package that appears to solve this problem called isomorphic-style-loader. It appears to be a replacement for style-loader. https://github.com/kriasoft/isomorphic-style-loader. Would people be open to this upgrade?

**Comment by altayaydemir** [comment]
the problem that you've defined above wouldn't appear on the production build. it happens because we don't extract css on development phase.

actually, we're already using the package that you've suggested:
- https://github.com/barbar/vortigern/blob/master/package.json#L76
- https://github.com/barbar/vortigern/blob/master/config/webpack/server.js#L50-L54

**Comment by mostlyjason** [comment]
Ahh thanks I don't know how I missed that! Thanks for the tip on the production build. I'm going to close this.
